//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int Id_Product_Sale { get; set; }
        public System.DateTime Sale_date { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public int Amount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
